### ISSUE TITLE
[Proposal] Change LICENSE from MIT to Apache 2.0

### ISSUE THREAD

**Issue by git-hulk** [xdblab/xdb#3]
MIT and Apache 2.0 are good choices for individual open-source projects. But I guess it would be better to use Apache 2.0 since it has extra requirements about using the trademark of the project. And secondly, we don't need to ask contributors to approve if plan to donate the project to the ASF incubator. I see xdb-apis has been under Apache 2.0 license, So I guess it should be good to change the current project to that as well.

How do you feel about this? @longquanzheng @zklgame 

I will raise PR to resolve this if sounds good to you.

**Comment by longquanzheng** [comment]
👍 yes! I talked to @zklgame and she agreed with it too

**Comment by longquanzheng** [comment]
https://github.com/xdblab/xdb/pull/5
